In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_excel('Análisis_de_piso.xlsx')
df.head()

,Unnamed: 0,Leads Piso 2024,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 41,Unnamed: 42,979,811,Unnamed: 45,Unnamed: 46,Factor minimo mejor vendedor,Factor minimo mejor vendedor .1,Unnamed: 49,Unnamed: 50
0,NaN,459,27,95,110,65,107,88,59,40,...,RAKING VENTAS,Dependencia de Piso,Historico de PDM,Historico de SDC,Conversion PDM,Conversion SDC,Factor PDM,Factor SDC,Raking PDM,Raking SDC
1,Asesor,feb,mar,abr,may,jun,jul,ago,sep,oct,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,ABIGAIL,23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,23,0,1,5,1,0,1.00,5.00,1,20
3,ALAN GONZALES,1,NaN,NaN,NaN,NaN,NaN,NaN,,NaN,...,6,0.61,59,40,0.31,0.02,3.28,2.22,7,10
4,ALICIA LEDESMA,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,...,0,0,1,1,0,0,0.00,0.00,NaN,NaN

In [4]:
df_sinnulos = df.isnull().sum()
df_sinnulos

Unnamed: 0                                1
Leads Piso 2024                          19
Unnamed: 2                               31
Unnamed: 3                               23
Unnamed: 4                               28
Unnamed: 5                               30
Unnamed: 6                               29
Unnamed: 7                               30
Unnamed: 8                               27
Unnamed: 9                               31
Unnamed: 10                              25
Unnamed: 11                              31
Leads Piso 2025                          30
Unnamed: 13                              30
Unnamed: 14                              33
Unnamed: 15                              31
Total                                     0
Total Ajustado                            0
Raking                                    2
Raking ajustado                           2
Ventas Piso 2024                          0
Unnamed: 21                              38
Unnamed: 22                              35
Unnamed: 23                              39
Unnamed: 24                              38
Unnamed: 25                              36
Unnamed: 26                              36
Unnamed: 27                              35
Unnamed: 28                              38
Unnamed: 29                              34
Unnamed: 30                              34
Unnamed: 31                              35
Ventas Piso 2025                         33
Unnamed: 33                              35
Unnamed: 34                               0
Unnamed: 35                              34
* se actualiza al reportar en Sale-U     38
Unnamed: 37                               1
Unnamed: 38                               1
Unnamed: 39                               1
263                                      15
Unnamed: 41                               1
Unnamed: 42                               1
979                                       1
811                                       2
Unnamed: 45                               3
Unnamed: 46                               2
Factor minimo mejor vendedor              1
Factor minimo mejor vendedor .1           1
Unnamed: 49                              18
Unnamed: 50                              15
dtype: int64

In [32]:
# Seleccionamos las columnas de meses (leads 2024, leads 2025, ventas 2024, ventas 2025)
columnas_meses = df.columns[1:16].tolist() + df.columns[20:37].tolist()

# Rellenamos esas columnas con 0
df[columnas_meses] = df[columnas_meses].fillna(0)

In [33]:
df[columnas_meses].isnull().sum()

Leads Piso 2024                          0
Unnamed: 2                               0
Unnamed: 3                               0
Unnamed: 4                               0
Unnamed: 5                               0
Unnamed: 6                               0
Unnamed: 7                               0
Unnamed: 8                               0
Unnamed: 9                               0
Unnamed: 10                              0
Unnamed: 11                              0
Leads Piso 2025                          0
Unnamed: 13                              0
Unnamed: 14                              0
Unnamed: 15                              0
Ventas Piso 2024                         0
Unnamed: 21                              0
Unnamed: 22                              0
Unnamed: 23                              0
Unnamed: 24                              0
Unnamed: 25                              0
Unnamed: 26                              0
Unnamed: 27                              0
Unnamed: 28                              0
Unnamed: 29                              0
Unnamed: 30                              0
Unnamed: 31                              0
Ventas Piso 2025                         0
Unnamed: 33                              0
Unnamed: 34                              0
Unnamed: 35                              0
* se actualiza al reportar en Sale-U     0
dtype: int64

In [34]:
df.isnull().sum()

Unnamed: 0                                1
Leads Piso 2024                           0
Unnamed: 2                                0
Unnamed: 3                                0
Unnamed: 4                                0
Unnamed: 5                                0
Unnamed: 6                                0
Unnamed: 7                                0
Unnamed: 8                                0
Unnamed: 9                                0
Unnamed: 10                               0
Unnamed: 11                               0
Leads Piso 2025                           0
Unnamed: 13                               0
Unnamed: 14                               0
Unnamed: 15                               0
Total                                     0
Total Ajustado                            0
Raking                                    2
Raking ajustado                           2
Ventas Piso 2024                          0
Unnamed: 21                               0
Unnamed: 22                               0
Unnamed: 23                               0
Unnamed: 24                               0
Unnamed: 25                               0
Unnamed: 26                               0
Unnamed: 27                               0
Unnamed: 28                               0
Unnamed: 29                               0
Unnamed: 30                               0
Unnamed: 31                               0
Ventas Piso 2025                          0
Unnamed: 33                               0
Unnamed: 34                               0
Unnamed: 35                               0
* se actualiza al reportar en Sale-U      0
Unnamed: 37                               1
Unnamed: 38                               1
Unnamed: 39                               1
263                                      15
Unnamed: 41                               1
Unnamed: 42                               1
979                                       1
811                                       2
Unnamed: 45                               3
Unnamed: 46                               2
Factor minimo mejor vendedor              1
Factor minimo mejor vendedor .1           1
Unnamed: 49                              18
Unnamed: 50                              15
dtype: int64

In [35]:
df.head()

,Unnamed: 0,Leads Piso 2024,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 41,Unnamed: 42,979,811,Unnamed: 45,Unnamed: 46,Factor minimo mejor vendedor,Factor minimo mejor vendedor .1,Unnamed: 49,Unnamed: 50
0,NaN,459,27,95,110,65,107,88,59,40,...,RAKING VENTAS,Dependencia de Piso,Historico de PDM,Historico de SDC,Conversion PDM,Conversion SDC,Factor PDM,Factor SDC,Raking PDM,Raking SDC
1,Asesor,feb,mar,abr,may,jun,jul,ago,sep,oct,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,ABIGAIL,23,0,0,0,0,0,0,0,0,...,23,0,1,5,1,0,1.00,5.00,1,20
3,ALAN GONZALES,1,0,0,0,0,0,0,,0,...,6,0.61,59,40,0.31,0.02,3.28,2.22,7,10
4,ALICIA LEDESMA,0,0,1,0,0,0,0,0,0,...,0,0,1,1,0,0,0.00,0.00,NaN,NaN

In [36]:
df.to_csv("Analisisdepiso_sin_nulos.csv")

Base de datos: Base de Leads

In [7]:
df1 = pd.read_excel('Base_de_Leads.xlsx')
df1.head()

,Fecha de Alta,Mes Lead,AgLead,Titulo,Nombre,Telefono,Correo,Producto,Temperatura,Comentario,Asesor,Fuente,Origen,
0,2025-11-30 08:38:00,11,834956f716e7ddae82527bf81c29ebc8,Lead ANGE,Apolonio Torres Perez,NaN,NaN,EMZOOM,Lead Muy Interesado,Se reactiva lead para captura de ventaFinal:EM...,CESAR DE JESUS PESTAÃ‘A,11.Origen Personalizado/Calle,PLAZA ANGELOPOLIS,1 Ventas
1,2025-11-29 21:17:00,11,13ee2f21ed8506825e8591bf1abdab51,Lead ANGE,Javier Nieto,NaN,NaN,GS4 MAX,Lead Interes Medio,SE LE CONTACTA EN PLAZA ANGELOPOLIS Final:GS4 ...,MAURICIO ALFREDO VAZQUEZ FARFAN,11.Origen Personalizado/Calle,PLAZA ANGELOPOLIS,Finalizado
2,2025-11-29 20:48:00,11,fad33b39f526b4ebe04a4b7e86002d5a,Lead ANGE,Ismael Segovia Banos,NaN,NaN,GS4 MAX,Lead Muy Interesado,SE INTERESA POR GS4 Final:GS4 MAX HEV,MAURICIO ALFREDO VAZQUEZ FARFAN,11.Origen Personalizado/Calle,PLAZA ANGELOPOLIS,1 Ventas
3,2025-11-29 16:11:00,11,e495cd540b7c7dc55b516fbdc7ea8bf0,Lead ANGE,Luis Jaime Estrada,NaN,NaN,EMKOO,Lead Muy Interesado,ofrecÃ­ tambiÃ©n GS4 y emko hv Pidieron:EMKOO HEV,RICARDO SILVA HERAS,11.Origen Personalizado/Calle,PLAZA ANGELOPOLIS,Contactado
4,2025-11-29 16:08:00,11,4d2b212032284fa42fa64a493e34c4ed,Lead ANGE,Hector Hamley,NaN,NaN,EMKOO,Lead Interes Medio,interÃ©s Pidieron:EMKOO HEV,RICARDO SILVA HERAS,11.Origen Personalizado/Calle,PLAZA ANGELOPOLIS,Contactado

In [15]:
df1_sinnulos = df1.isnull().sum()
df1_sinnulos

Fecha de Alta      0
Mes Lead           0
AgLead             0
Titulo             0
Nombre             0
Telefono         210
Correo           210
Producto          14
Temperatura        0
Comentario         0
Asesor             0
Fuente             0
Origen             0
                   0
dtype: int64

In [16]:
df1.shape

(210, 14)

In [20]:
df1_sinnul = df1.drop(columns=['Telefono', 'Correo'])

In [22]:
print(df1_sinnul.isnull().sum())

Fecha de Alta     0
Mes Lead          0
AgLead            0
Titulo            0
Nombre            0
Producto         14
Temperatura       0
Comentario        0
Asesor            0
Fuente            0
Origen            0
                  0
dtype: int64

In [27]:
df1_sinnul['Producto'] = df1_sinnul['Producto'].fillna('No registrado')

In [30]:
print(df1_sinnul.isnull().sum())   
print(df1_sinnul.head())

Fecha de Alta    0
Mes Lead         0
AgLead           0
Titulo           0
Nombre           0
Producto         0
Temperatura      0
Comentario       0
Asesor           0
Fuente           0
Origen           0
                 0
dtype: int64
        Fecha de Alta  Mes Lead                            AgLead      Titulo  \
0 2025-11-30 08:38:00        11  834956f716e7ddae82527bf81c29ebc8  Lead  ANGE
1 2025-11-29 21:17:00        11  13ee2f21ed8506825e8591bf1abdab51  Lead  ANGE
2 2025-11-29 20:48:00        11  fad33b39f526b4ebe04a4b7e86002d5a  Lead  ANGE
3 2025-11-29 16:11:00        11  e495cd540b7c7dc55b516fbdc7ea8bf0  Lead  ANGE
4 2025-11-29 16:08:00        11  4d2b212032284fa42fa64a493e34c4ed  Lead  ANGE

                   Nombre Producto          Temperatura  \
0  Apolonio Torres Perez    EMZOOM  Lead Muy Interesado
1           Javier Nieto   GS4 MAX   Lead Interes Medio
2    Ismael Segovia Banos  GS4 MAX  Lead Muy Interesado
3  Luis Jaime  Estrada       EMKOO  Lead Muy Interesado
4       Hector  Hamley       EMKOO   Lead Interes Medio

                                          Comentario  \
0  Se reactiva lead para captura de ventaFinal:EM...
1  SE LE CONTACTA EN PLAZA ANGELOPOLIS Final:GS4 ...
2              SE INTERESA POR GS4 Final:GS4 MAX HEV
3  ofrecÃ­ tambiÃ©n GS4 y emko hv Pidieron:EMKOO HEV
4                        interÃ©s Pidieron:EMKOO HEV

                            Asesor                         Fuente  \
0          CESAR DE JESUS PESTAÃ‘A  11.Origen Personalizado/Calle
1  MAURICIO ALFREDO VAZQUEZ FARFAN  11.Origen Personalizado/Calle
2  MAURICIO ALFREDO VAZQUEZ FARFAN  11.Origen Personalizado/Calle
3              RICARDO SILVA HERAS  11.Origen Personalizado/Calle
4              RICARDO SILVA HERAS  11.Origen Personalizado/Calle

              Origen
0  PLAZA ANGELOPOLIS    1 Ventas
1  PLAZA ANGELOPOLIS  Finalizado
2  PLAZA ANGELOPOLIS    1 Ventas
3  PLAZA ANGELOPOLIS  Contactado
4  PLAZA ANGELOPOLIS  Contactado

In [31]:
df1_sinnul.to_csv("BasedeLeads_sin_nulos.csv")